byod:
  ray_ecr: rayproject
  ray_cr_repo: ray
  ray_ml_cr_repo: ray-ml
  byod_ecr: 029272617770.dkr.ecr.us-west-2.amazonaws.com
  aws_ecr: 029272617770.dkr.ecr.us-west-2.amazonaws.com
  gcp_ecr: us-west1-docker.pkg.dev/anyscale-oss-ci
state_machine:
  aws_bucket: ray-ci-results
